change-type:
    after-string: ']'
    before-string: '['
    destination: title
    instructions: What kind of change?
    modifiable: true
    format: "%-12s"
    options:
        - fix
        - add
        - refactor
        - clean-up
    type: select
breaking-indicator:
    after-string: ': '
    allow-empty: true
    destination: title
    empty-selection-text: Skip
    instructions: Skip unless breaking change
    options:
        - breaking
    type: select
commit-title:
    destination: title
    placeholder: Commit Title
    type: text
commit-description:
    allow-empty: true
    destination: body
    instructions: Please describe your changes.
    type: multiline-text
code-sections:
    allow-empty: true
    before-string: "\nCode Sections: "
    destination: body
    instructions: Which section(s) of the codebase?
    modifiable: true
    options:
        - tags
        - bookmarks
        - ui
        - css
        - ux
        - config
        - meta
        - tests
        - oauth
        - migrations
        - archives
        - infrastructure
    record-as: joined-string
    type: multi-select
ticket-number:
    allow-empty: true
    before-string: "\n\nTicket: "
    data-type: integer
    destination: body
    instructions: Associated Ticket Number (if any)
    type: text
meta_element_changelog:
    display_aliases:
        fix: "fixed"
        add: "added"
        refactor: "refactored"
        clean-up: "cleaned"
