require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops

Layout/ExtraSpacing:
  Enabled: false

# because there's no good suggested alternative
RSpec/LetSetup:
  Enabled: false

# old man shouting at clouds
RSpec/MessageSpies:
  Enabled: false


# these are fine for ActiveRecord but
# aren't supported by Mongoid
Rails/FindEach:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false

# stop effing with my log messages!
Rails/EagerEvaluationLogMessage:
  Enabled: false

# no shit, but don't make me put rubocop comments in a view. not cool
Rails/OutputSafety:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc

#I'll nest if i wanna!
RSpec/NestedGroups:
  Enabled: false
