#!/usr/bin/env bash


echo "Starting docker/serve"


# Exit on error
set -e

# I don't know why this error is happening or even what is calling git
# BUUUTT it happens after or during the bundle install
# bb_rails-1        | fatal: detected dubious ownership in repository at '/app'
# bb_rails-1        | To add an exception for this directory, call:
# bb_rails-1        |
# bb_rails-1        | 	git config --global --add safe.directory /app
git config --global --add safe.directory /app



ENV_FILE=".env"
DELAYED_JOB_FILE="bin/delayed_job"
cd /app # move to the root of the project
source "scripts/bash_helpers/colors.sh"
source "scripts/bash_helpers/get_env_key.sh"
source "scripts/bash_helpers/migrations.sh"



# clean up after the last run
# any old server.pid file at this point is guaranteed bad
if [ -f tmp/pids/server.pid ]; then
  echo "Removing old server.pid file"
  rm tmp/pids/server.pid
fi

cd /app
echo "BUNDLE_PATH: ${BUNDLE_PATH}"
bundle install


# Make sure you've defined a host name
hostname=$(get_env_key 'HOST_NAME')
if [ -z "$hostname" ]; then
  echo $RED"HOST_NAME is not set"$NOCOLOR
  echo "Set it in the .env file"
  echo "By default you probably want to set it to 'localhost'"
  echo "ex: HOST_NAME=localhost"
  echo "Check the README ways to give it a better name."
  exit 78 # EX_CONFIG (78)  Something was found in an unconfigured or misconfigured state.
else
  echo $GREEN"HOST_NAME is set to \"$hostname\""$NOCOLOR
  echo "If this is not correct please update the .env file"
  echo "It will effect your ability to log in."
fi
ssh_host=$(get_env_key 'HOST_USES_SSH')
if [ -z "$ssh_host" ]; then
  ssh_host="false"
fi

# Make sure you've defined a port (defaults in .env.sample is 3334)
port=$(get_env_key 'PORT')
if [ -z "$port" ]; then
  echo $RED"PORT is not set"$NOCOLOR
  echo "Set it in the .env file"
  echo "By default you probably want to set it to 3334"
  echo "ex: PORT=3334"
  echo "Lots of development tools use 3000, so this 3334 won't interfere with them."
  exit 78 # EX_CONFIG (78)  Something was found in an unconfigured or misconfigured state.
else
  echo $GREEN"PORT is set to \"$port\""$NOCOLOR
  echo "If this is not correct please update the .env file"
fi

# and a mongodb url
mongodb_url=$(get_env_key 'MONGODB_URL')
if [ -z "$mongodb_url" ]; then
  echo $RED"MONGODB_URL is not set"$NOCOLOR
  echo "Set it in the .env file"
  echo "By default you probably want to set it to 'mongodb://bb_mongodb:27017'"
  echo "ex: MONGODB_URL=mongodb://bb_mongodb:27017"
  exit 78 # EX_CONFIG (78)  Something was found in an unconfigured or misconfigured state.
else
  echo $GREEN"MONGODB_URL is set to \"$mongodb_url\""$NOCOLOR
  echo "If this is not correct please update the .env file"
fi


run_next_migration_file_if_present


search_enabled=$(get_env_key 'SEARCH_ENABLED')
if [ -z "$search_enabled" ]; then
  echo $RED"SEARCH_ENABLED is not set"$NOCOLOR
  echo "Search will be unavailable"
  echo "Set it to true in the .env file to enable search"
  echo "ex: SEARCH_ENABLED=true"

elif [ "$search_enabled" == "true" ]; then
  echo $GREEN"Search is enabled"$NOCOLOR
  echo "If this is not correct please update the .env file"
else
  echo $YELLOW"Search is disabled via .env"$NOCOLOR
fi

worker_count=$(get_env_key 'DELAYED_JOB_WORKERS')
if [ -z "$worker_count" ]; then
  echo $YELLOW"DELAYED_JOB_WORKERS is not set"$NOCOLOR
  echo "Will use 2 workers by default."
  echo "Configure this as an integer in your .env file"
  worker_count=2
else
  echo $GREEN"DELAYED_JOB_WORKERS is set to \"$worker_count\""$NOCOLOR
  echo "If this is not correct please update the .env file"
fi

echo "Starting $worker_count Delayed Job Workers"
# Start the Delayed Job Workers
$DELAYED_JOB_FILE -n $worker_count start & disown


if [ "$ssh_host" == "false" ]; then
  visitable_url="http://$hostname:$port"
else
  visitable_url="https://$hostname"
fi
echo $GREEN"VISIT YOUR BACKUP BRAIN AT $visitable_url"$NOCOLOR
# Start Rails
# bundle exec rails server -p $port -u puma
bundle exec rails server -b '0.0.0.0' -p $port -u puma
